- hosts: "*"
  become: yes
  tasks:
  - name: Configure sysctl
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: "{{item.name}}="
      line: "{{item.name}}={{item.value}}"
      state: present
    with_items:
      # Forwarding
      - { name: "net.ipv4.ip_forward", value: "1" }
      - { name: "net.ipv6.conf.all.forwarding", value: "1" }
      - { name: "net.ipv4.tcp_syncookies", value: "1" }
      # 10GbE
      - { name: "net.core.rmem_max", value: "134217728"}
      - { name: "net.core.wmem_max", value: "134217728"}
      - { name: "net.ipv4.tcp_rmem", value: "4096 87380 134217728"}
      - { name: "net.ipv4.tcp_wmem", value: "4096 65536 134217728"}
      - { name: "net.core.netdev_max_backlog", value: "300000"}
      - { name: "net.ipv4.tcp_moderate_rcvbuf", value: "1"}
      - { name: "net.ipv4.tcp_no_metrics_save", value: "1"}
      - { name: "net.ipv4.tcp_congestion_control", value: "htcp"}
      - { name: "net.ipv4.tcp_mtu_probing", value: "1"}

# :vim: set sw=2 et ts=2 :
