- hosts: "*"
  become: yes
  tasks:
  - name: Populating /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: " {{item}}$"
      line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
      state: present
    with_items: "{{ groups['all'] }}"

# :vim: set sw=2 et ts=2 :

