- hosts: "*"
  become: yes
  gather_facts: False
  tasks:
  - name: Must have python
    raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
    changed_when: False # XXX I don't like it to "infect" Ansible output

# :vim: set sw=2 et ts=2 :
